<?php

namespace Test\w3ocom\FieldsPack;

use w3ocom\FieldsPack\FieldsPackOpt;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-08-24 at 19:30:12.
 */
class FieldsPackOptTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var FieldsPackOpt
     */
    protected $object;
    
    protected $is_opt_mode = true;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->object = new FieldsPackOpt();
    }

    /*
     * @covers w3ocom\FieldsPack\FieldsPackOpt::__construct
     */
    public function testConstruct() {
        $obj = new FieldsPackOpt("ntest");
        $this->assertEquals("\0\0", $obj->pack(['test' => 0]));
        
        $this->expectException(\Exception::class);
        $obj = new FieldsPackOpt("n");
    }
    /**
     * Provider of format -> length
     * 
     * @return array
     */
    public function formatLenProvider() {
        $arr = [];
        foreach([
            'J' => 8,
            'Q' => 8,
            'P' => 8,
            'N' => 4,
            'L' => 4,
            'V' => 4,
            'l' => 4,
            'n' => 2,
            'v' => 2,
            'C' => 1,
        ] as $fmtC => $fmtLen) {
            $arr[] = [$fmtC, $fmtLen];
        }
        return $arr;
    }

    public function goodVariantsProvider() {
        return [
            'ntest' => 
                ['ntest', [
                    'test' => 'n'
                ]],

            'Ca/Cb/Cc' =>
                ['Ca/Cb/Cc', [
                    'a' => 'C',
                    'b' => 'C',
                    'c' => 'C',
                ]],

            'NNN/nnn/CCC/JJJ' =>
                ['NNN/nnn/CCC/JJJ', [
                    'NN' => 'N',
                    'nn' => 'n',
                    'CC' => 'C',
                    'JJ' => 'J',
                ]]
            ];
    }

    public function badVariantsProvider() {
        return [
            'EmptyNameTest' => 
                ['Ctest/n', "Empty field name"],

            'BadFieldsCount' =>
                ['Ca//Cb', 'Error unpack-format parsing'],
        ];
    }

    public function packUnpackProvider() {
        $arr = [
            [ "Cone", 
                chr(123) . chr(111),
                [
                    'one' => 123,
                    '*' => chr(111)
                ]
            ],
            [ "C*one",
                chr(1) . 'a',
                [
                    'one' => 'a'
                ]
            ],
            [ "C*x",
                chr(0) . 'test',
                'test'
            ],
        ];
        if ($this->is_opt_mode) {
            $arr[] =
            [ 'C_f/Cone',
                chr(1) . chr(2),
                [
                    'one' => 2
                ]
            ];
            $arr[] =
            [ 'C_f/Cf1',
                chr(1) . chr(2) . chr(3),
                [
                    'f1' => 2,
                    '*' => chr(3)
                ]
            ];
            $arr[] =
            [ 'C_f/C*str',
                chr(1) . chr(2) . chr(3) . chr(4),
                [
                    'str' => chr(3) . chr(4),
                ]
            ];

        }
        
        return $arr;
    }

    public function unpackBadProvider() {
        return [
            ['Cone/Ctwo',
                chr(1),
                "String too short"
            ]
        ];
    }

    /**
     * @dataProvider packUnpackProvider
     * @covers w3ocom\FieldsPack\FieldsPackOpt::pack
     */
    public function testPack($fields_un, $pk, $arr) {
        $this->object->setFields($fields_un);
        $this->assertEquals($pk, $this->object->pack($arr));
    }
    
    public function testPackLogicException() {
        $this->object->setFields("Cf1/Cf2");
        $this->object->header_bytes = 1;
        $this->expectException(\LogicException::class);
        $pk = $this->object->pack(['f1' => 1, 'f2' => 2]);
    }

    public function testPackOutOfBoundsException() {
        $this->object->setFields("C_f/Cf1/Cf2");
        $this->expectException(\OutOfBoundsException::class);
        $pk = $this->object->pack(['f1' => 1, 'f3' => null]);        
    }
    
    public function testUnpackIllegalRaw() {
        $obj = new FieldsPackOpt("n_f/Cf1");
        $this->assertTrue(is_string($obj->unpack('a')));
    }

    /**
     * @dataProvider unpackBadProvider
     * @dataProvider packUnpackProvider
     * @covers w3ocom\FieldsPack\FieldsPackOpt::unpack
     */
    public function testUnpack($fields_un, $pk, $arr) {
        $this->object->setFields($fields_un);
        if ($arr === 'test') {
            $arr = ['x' => '', '*' => $arr];
        } elseif (is_array($arr) && !isset($arr['*'])) {
            $arr['*'] = '';
        }
        $this->assertEquals($arr, $this->object->unpack($pk));
    }

    /**
     * @dataProvider goodVariantsProvider
     * @covers w3ocom\FieldsPack\FieldsPackMain::packFmtFields
     */
    public function testPackFmtFields($fields_un, $fields_arr) {
        $this->assertEquals($fields_un, $this->object->PackFmtFields($fields_arr));
    }
    
    /**
     * @covers w3ocom\FieldsPack\FieldsPackMain::setFields
     */
    public function testSetFields() {
        $this->assertFalse($this->object->SetFields("ntest"));

        // bad fields srting expected
        $this->assertTrue(is_string(
                $this->object->setFields('/*')
        ));
        
        if ($this->is_opt_mode) {
            // Good _f
            $this->assertFalse($this->object->SetFields("C_f/None/ntwo"));

            // Bad format _f
            $this->assertTrue(is_string(
                $this->object->SetFields("X_f/None/ntwo")
            ));

            // too many fields
            $this->assertTrue(is_string(
                $this->object->SetFields("C_f/Nf0/nf1/Cf2/nf3/Cf4/Cf5/Cf6/Cf7/Cf8")
            ));

            // OK
            $this->assertFalse(is_string(
                $this->object->SetFields("C_f/Nf0/nf1/Cf2/nf3/Cf4/Cf5/Cf6/Cf7")
            ));
        }
        
        // *-mode
        $this->assertFalse($this->object->SetFields("n*one/C*two"));

        // Bad-fmt-* 
        $this->assertTrue(is_string(
            $this->object->SetFields("n*one/X*two")
        ));

    }
    
    /**
     * @dataProvider formatLenProvider
     * @covers w3ocom\FieldsPack\FieldsPackMain::fmtMultiBytesLen
     */
    public function testFmtMultiBytesLen($fmtC, $fmtLen) {
        $this->assertEquals($fmtLen, FieldsPackOpt::FmtMultiBytesLen($fmtC));
    }
    
    /*
     * @covers w3ocom\FieldsPack\FieldsPackOpt::unpack
     */
    public function testUnpackIncH() {
        $this->object->setFields('C_f/Cf2/Cf3');
        $pk = $this->object->pack(['f2' => 2, 'f3' => 3]);
        $this->assertEquals(chr(3) . chr(2) . chr(3), $pk);
        // set inc_h
        $this->object->inc_h = true;
        $un = $this->object->unpack($pk);
        $this->assertArrayHasKey('_h', $un);
    }
}
